language: php

sudo: false

php:
  - 5.4
  - 7.0

before_script:
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./webroot ./plugins/IctCollege/CoordinatorApprovedSelector/src"

notifications:
  email: false

cache:
  directories:
  - vendor
  - $HOME/.composer/config
