<?php
namespace App\Controller\Admin;

use App\Controller\AppController as BaseController;

class AppController extends BaseController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->viewBuilder()->layout('admin');

        $this->Crud->mapAction('add', [
            'messages' => [
                'success' => [
                    'element' => 'success',
                    'params' => [
                        'class' => false
                    ]
                ]
            ]
        ]);

        $this->Crud->mapAction('edit', [
            'messages' => [
                'success' => [
                    'element' => 'success',
                    'params' => [
                        'class' => false
                    ]
                ]
            ]
        ]);

        $this->Crud->mapAction('delete', [
            'messages' => [
                'success' => [
                    'element' => 'success',
                    'params' => [
                        'class' => false
                    ]
                ]
            ]
        ]);
    }
}
